package com.sliit.smartcampus.enums;

public enum CampusNotificationType {
    BOOKING_REQUEST_SUBMITTED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_CHANGED,
    TICKET_COMMENT_ADDED,
    TICKET_RESOLUTION_NOTE_ADDED,
    TICKET_PROGRESS_UPDATED,
    TECHNICIAN_UPDATE,
    DEADLINE_REMINDER
}